version: '3'
services:
 loki:
    user: root
    image: grafana/loki:latest
    container_name: loki-databases
    volumes:
     - ./config/loki-config.yml:/etc/config/loki-config.yml
     - ./rules/rules.yml:/etc/loki/rules/rules.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/config/loki-config.yml