version: '3'
services:
 loki:
    user: root
    image: grafana/loki:latest
    container_name: loki-databases
    volumes:
     - ./config/loki-config.yml:/etc/config/loki-config.yml:rw
     - ./rules/rules.yml:/etc/loki/rules/fake/rules.yml
     - ./data/loki/:/tmp/loki/ #mount thư mục liên quan chunk và index ra ngoài
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki-config.yml
    ports:
      - "3100:3100"    